[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Psychology of Mindful Communication for Conflict Resolution in the Workplace: Understanding the Importance of Mindful Communication for Effective Conflict Resolution in the Workplace"
