npm install
npx honkit epub ./ the-psychology-of-mindful-communication-for-conflict-resolution-in-the-workplace-understanding-the-importance-of-mindful-communication-for-effective-conflict-resolution-in-the-workplace.epub

ebook-convert the-psychology-of-mindful-communication-for-conflict-resolution-in-the-workplace-understanding-the-importance-of-mindful-communication-for-effective-conflict-resolution-in-the-workplace.epub the-psychology-of-mindful-communication-for-conflict-resolution-in-the-workplace-understanding-the-importance-of-mindful-communication-for-effective-conflict-resolution-in-the-workplace.pdf --no-chapters-in-toc --chapter-mark=none --pdf-page-numbers --disable-markup-chapter-headings --paper-size a5 --pdf-page-margin-bottom 36 --pdf-page-margin-left 36 --pdf-page-margin-right 36 --pdf-page-margin-top 36 --extra-css page_styles.css

ebook-convert the-psychology-of-mindful-communication-for-conflict-resolution-in-the-workplace-understanding-the-importance-of-mindful-communication-for-effective-conflict-resolution-in-the-workplace.epub the-psychology-of-mindful-communication-for-conflict-resolution-in-the-workplace-understanding-the-importance-of-mindful-communication-for-effective-conflict-resolution-in-the-workplace.mobi

ebook-convert the-psychology-of-mindful-communication-for-conflict-resolution-in-the-workplace-understanding-the-importance-of-mindful-communication-for-effective-conflict-resolution-in-the-workplace.epub the-psychology-of-mindful-communication-for-conflict-resolution-in-the-workplace-understanding-the-importance-of-mindful-communication-for-effective-conflict-resolution-in-the-workplace.azw3

ebook-convert the-psychology-of-mindful-communication-for-conflict-resolution-in-the-workplace-understanding-the-importance-of-mindful-communication-for-effective-conflict-resolution-in-the-workplace.epub the-psychology-of-mindful-communication-for-conflict-resolution-in-the-workplace-understanding-the-importance-of-mindful-communication-for-effective-conflict-resolution-in-the-workplace.docx --no-chapters-in-toc --chapter-mark=none --disable-markup-chapter-headings --docx-no-toc --docx-no-cover --docx-page-size=a5 --extra-css page_styles.css

